version: '3'
volumes:
  psql-data:

services:
  php-app:
    build: .
    container_name: php-quipux
    depends_on:
    - postgres
    volumes:
    - ./PHP:/var/www/html/
    ports:
    - 80:80
    - 443:443
    networks:
      app-env:

  postgres:
    image: postgres:10.1
    container_name: postgres
    environment:
    - POSTGRES_DB=quipux_comunidad
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    ports:
    - 5432:5432
    volumes:
    - ./postgres/script/:/docker-entrypoint-initdb.d
    - psql-data:/var/lib/posgresql/data
    networks:
      app-env:

networks:
  app-env:
